version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    
  pokemonapi:
    image: pokemonapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
